#!/bin/bash
#  Bash script to keep the mud up forever

# modify as necessary
dgddir=/home/erlends/gurba

########################################
logdir=$dgddir/lib/logs
logs="driver.log catch runtime log"
logfile=$logdir/driver.log

bindir=$dgddir/bin
driver=./driver
config=./mud.dgd

cd $dgddir

for f in $logs ; do mv -f $logdir/$f $logdir/$f.old > /dev/null 2>&1 ; done

date > $logfile
$bindir/$driver $dgddir/$config >> $logfile 2>&1

