#!/usr/bin/perl -w
my ($word);

sub rm_dir {
   my ($infile) = @_;

   if (-d $infile) {
      system("rm -rf $infile");
   }
}

if (!-f "scripts/create_data_dirs.pl") {
   print "Error I'm not in the right location.  You need to run this script\n";
   print "in the base directory gurablib.\n";
   print "\tcd to your gurbalib then type: scripts/create_data_dirs.pl\n";
   exit 1;
}

print "WARNING: You are about to remove all user data on your mud, are you sure you want to continue? (Y/n)";
chomp($word = <STDIN>);

if ($word eq "y" || $word eq "Y") {
} else {
   print "Aborting.\n";
   exit 1;
}

rm_dir("lib/data/banished");
rm_dir("lib/data/banned");
rm_dir("lib/data/banned/a");
rm_dir("lib/data/banned/b");
rm_dir("lib/data/banned/c");
rm_dir("lib/data/players");
rm_dir("lib/domains/gurba/data");
rm_dir("lib/domains/gurba/data/boards");
rm_dir("lib/kernel/daemons/data");
rm_dir("lib/kernel/lib/net");
rm_dir("lib/sys/daemons/data");
rm_dir("lib/sys/daemons/data/users");
rm_dir("lib/sys/daemons/data/users/a");
rm_dir("lib/sys/daemons/data/users/b");
rm_dir("lib/sys/daemons/data/users/c");
rm_dir("lib/sys/daemons/data/users/d");
rm_dir("lib/sys/daemons/data/users/e");
rm_dir("lib/sys/daemons/data/users/f");
rm_dir("lib/sys/daemons/data/users/g");
rm_dir("lib/sys/daemons/data/users/h");
rm_dir("lib/sys/daemons/data/users/i");
rm_dir("lib/sys/daemons/data/users/j");
rm_dir("lib/sys/daemons/data/users/k");
rm_dir("lib/sys/daemons/data/users/l");
rm_dir("lib/sys/daemons/data/users/m");
rm_dir("lib/sys/daemons/data/users/n");
rm_dir("lib/sys/daemons/data/users/o");
rm_dir("lib/sys/daemons/data/users/p");
rm_dir("lib/sys/daemons/data/users/q");
rm_dir("lib/sys/daemons/data/users/r");
rm_dir("lib/sys/daemons/data/users/s");
rm_dir("lib/sys/daemons/data/users/t");
rm_dir("lib/sys/daemons/data/users/u");
rm_dir("lib/sys/daemons/data/users/v");
rm_dir("lib/sys/daemons/data/users/w");
rm_dir("lib/sys/daemons/data/users/x");
rm_dir("lib/sys/daemons/data/users/y");
rm_dir("lib/sys/daemons/data/users/z");
rm_dir("lib/sys/data");
rm_dir("lib/tmp");
rm_dir("lib/logs");
rm_dir("lib/logs/errors");
rm_dir("lib/wiz");

print "You should run scripts/create_data_dirs.pl to recreate your data directories.\n";
