#!/usr/bin/perl -w
my ($word);

sub rm_dir {
   my ($infile) = @_;

   if (-d $infile) {
      system("rm -rf $infile");
   }
}

if (!-f "scripts/create_data_dirs") {
   print "Error I'm not in the right location.  You need to run this script\n";
   print "in the base directory gurablib.\n";
   print "\tcd to your gurbalib then type: scripts/clean_logs\n";
   exit 1;
}


rm_dir("lib/logs");
mkdir("lib/logs");
mkdir("lib/logs/errors");
mkdir("lib/logs/nobody");

