#!/usr/bin/perl

use strict;
use warnings;

# -linux options:
# -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4
#            -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -npsl -sai
#            -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1

# Our options:
my $options = "-nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci3 " .
	"-cli3 -d0 -di1 -nfc1 -i3 -ip0 -l80 -npcs -npsl -sai -brf " .
	"-saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1 -nlp";

my $indent = $ENV{"INDENT"};
if (!$indent || $indent eq "") {
	$indent = "indent";
}

my ($one) = @ARGV;

if (!$one) {
	print "Usage: $0 file.c\n" .
		"\twill create a new file file.c.new that is indented.\n";
	exit 1;
}

my $version = `indent --version`;

if ($version =~ /GNU indent (.*)/) {
	print "Calling indent $options $one -o $one.new\n";
	system("indent $options $one -o $one.new\n");
} else {
	print "Error unable to find GNU indent in your path.\n";
	print "If you have GNU indent you can set the environemt varilable " .
		"INDENT\n";
}
