#!/bin/bash

MUDNAME=""
REGEXP=0

find_cc() {
  which cc 2>/dev/null
}

ask_mudname() {
  echo -n "Your mud should have a name, please enter one : "
  read name
  if [ ! -z "${name}" ]; then
  echo -n ${name}" will be the name of your mud. Is this correct? (y/N) : "
    read var
    if [ -z "${var}" -o "${var}" != "y" ]; then
      return
    else
      MUDNAME=${name}
    fi
  fi
}

ask_regexp() {
  echo -n "Do you want to use the regexp extension? (y/N) : "
  read var

  if [ -x "${var}" -o "${var}" != "y" ]; then
    REGEXP=0
  else
    REGEXP=1
  fi
}


CC=`find_cc`

if [ -z "$CC" ]; then
  echo "No compiler found, cannot continue"
  exit 1
fi

PWD=`pwd`
CMD=$0

DIR=${PWD}/${CMD}
DIR=${DIR%%installer}../

cd ${DIR}
echo -n "Using "`pwd`" as base directory, is this ok? (Y/n) : "

read var

[ -z "${var}" -o "${var}" != "n" ] || exit 1

if [ "$1" == "--clean" ]; then
  rm -f scripts/.instrc
fi

if [ -f scripts/.instrc ]; then
  . scripts/.instrc
else
  ask_regexp
  echo "REGEXP=${REGEXP}">scripts/.instrc
fi
  
echo "Compiling driver.."

cd contrib/DGD/src

make clean

if [ $REGEXP -eq 1 ]; then
  if [ ! -e "regexp.c" ]; then
    cp ../../rgx-0.5/regexp.c ./
    cp -r ../../rgx-0.5/libiberty ./
    patch <../../rgx-0.5/Makefile.diff
  fi
else
  if [ -e "regexp.c" ]; then
    rm regexp.c
    rm -rf libiberty
    patch -R <../../rgx-0.5/Makefile.diff
  fi
fi
  
make && make install || exit

cd ../doc/kfun/
cp * ../../../../lib/doc/kfun/

cd ../../../../

TD=`pwd`
TD=${TD//\//\\\/}


if [ ! -f gurba.dgd ]; then
  cat net.dgd | sed -e "s/\/gurbalib/${TD}/g" >./gurba.dgd
fi

echo "BASEDIR="`pwd` >.basedir

if [ ! -f lib/kernel/include/mudname.h ]; then
  while [ -z "${MUDNAME}" ]; do
    ask_mudname
  done

  echo "Using mudname: " ${MUDNAME}
fi

cat lib/kernel/include/mudname.h.default | sed -e "s/MUD_NAME  \"GurbaLib\"/MUD_NAME  \"${MUDNAME}\"/" -e "s/IMUD_NAME \"GurbaLib\"/IMUD_NAME \"${MUDNAME}\"/" >./tmpfile && mv tmpfile lib/kernel/include/mudname.h

echo "All done."
echo "You may want to review lib/kernel/include/std.h to change your email address or such."
echo "To start the mud, type 'bin/driver gurba.dgd'"


