#!/bin/bash
ROOT=.

if [ -d $ROOT/lib/logs ]; then
	LOG=$ROOT/lib/logs/gurba-driver.log
	mv $LOG $LOG.old
else
	echo "Cannot locate $ROOT/lib/logs"
	echo "did you run $ROOT/scripts/create_data_dirs?"
	exit 1
fi

if [ -f $ROOT/bin/dgd ]; then
	if [ -f $ROOT/dump ]; then
		echo DGD starting from dump...
		$ROOT/bin/dgd $ROOT/mud.dgd $ROOT/dump >& $LOG
	else
		echo DGD starting from scratch...
		$ROOT/bin/dgd $ROOT/mud.dgd >& $LOG
	fi
fi
