#!/bin/bash

if [ -d ./lib/logs ]; then
	LOG=./lib/logs/gurba-driver.log
	mv $LOG $LOG.old
else
	echo "Cannot locate ./lib/logs"
	echo "did you run scripts/create_data_dirs?"
	exit 1
fi

if [ -f ./bin/dgd ]; then
	if [ -f ./dump ]; then
		echo DGD starting from dump...
		./bin/dgd ./mud.dgd ./dump >& $LOG
	else
		echo DGD starting from scratch...
		./bin/dgd ./mud.dgd >& $LOG
	fi
fi
