#define DIR "/domains/nokicliffs"
#define NOKICLIFFS_AREA "noki-cliffs"
#define NOKICLIFFS_VOID DIR + "/rooms/void.c"
#define NOKICLIFFS_DOOMSPIRE_START DIR + "/rooms/doomspire/doomspire_start.c"
#define NOKICLIFFS_OAK_GROVE_START DIR + "/rooms/oak_grove/oak_grove_start.c"
#define NOKICLIFFS_CANDYLAND_START DIR + "/rooms/candyland/candyland_start.c"
#define NOKICLIFFS_MURKY_MISTS_START DIR + "/rooms/murky_mists/murky_mists_start.c"
#define NOKICLIFFS_ABBEY_START DIR + "/rooms/abbey_of_law/abbey_of_law_start.c"
#define NOKICLIFFS_DEN_START DIR + "/rooms/den_of_chaos/den_of_chaos_start.c"
#define NOKICLIFFS_HALL_START DIR + "/rooms/hall_of_balance/hall_of_balance_start.c"
#define NOKICLIFFS_DEN_START DIR + "/rooms/den_of_chaos/den_of_chaos_start.c"
#define NOKICLIFFS_BASE_CAMP DIR + "/rooms/cliffs/base_camp.c"
#define NOKICLIFFS_BRAIN_IN_JAR DIR + "/obj/brain_in_jar.c"
#define NOKICLIFFS_BRAIN DIR + "/obj/brain.c"
#define TELL_ROOM(o, str) o->query_environment()->tell_room(o, str)
#define WIZHAT_COST 10
#define NOKICLIFFS_WEAPONS_DIR DIR + "/obj/weapons"
#define NOKICLIFFS_ARMOURS_DIR DIR + "/obj/armours"
#define NOKICLIFFS_MONSTERS_DIR DIR + "/monsters"
#define NOKICLIFFS_BRAIN_GUARD NOKICLIFFS_MONSTERS_DIR + "/brain_guard.c"
#define NOKICLIFFS_SHARD_QUEST "BalanceQuest"
#define NOKICLIFFS_SHARD_QUEST_XP_REWARD 5000
#define NOKICLIFFS_LAW_SHARD DIR + "/obj/law_shard"
#define NOKICLIFFS_CHAOS_SHARD DIR + "/obj/chaos_shard"
#define NOKICLIFFS_CHAOSBLADE NOKICLIFFS_WEAPONS_DIR + "/chaosblade"
#define NOKICLIFFS_CHAOSDEMON NOKICLIFFS_MONSTERS_DIR + "/chaosdemon"
#define NOKICLIFFS_LAWBRINGER NOKICLIFFS_WEAPONS_DIR + "/lawbringer"
#define NOKICLIFFS_DIMENSIONAL_BEADS DIR + "/obj/dimensional_beads"
