#define DIR "/domains/nokicliffs"
#define NOKICLIFFS_AREA "noki-cliffs"
#define NOKICLIFFS_OAK_GROVE_START DIR + "/rooms/oak_grove/oak_grove_start.c"
#define NOKICLIFFS_DOOMSPIRE_START DIR + "/rooms/doomspire/doomspire_start.c"
#define NOKICLIFFS_BASE_CAMP DIR + "/rooms/cliffs/base_camp.c"
#define NOKICLIFFS_BRAIN DIR + "/obj/brain.c"
#define TELL_ROOM(o, str) o->query_environment()->tell_room(o, str)
#define WIZHAT_COST 10
#define NOKICLIFFS_WEAPONS_DIR DIR + "/obj/weapons"
#define NOKICLIFFS_ARMOURS_DIR DIR + "/obj/armours"
#define NOKICLIFFS_MONSTERS_DIR DIR + "/monsters"
#define NOKICLIFFS_BRAIN_GUARD NOKICLIFFS_MONSTERS_DIR + "/brain_guard.c"
#define NOKICLIFFS_SHARD_QUEST "Quest for Balance"
#define NOKICLIFFS_LAW_SHARD DIR + "/obj/law_shard"
#define NOKICLIFFS_CHAOS_SHARD DIR + "/obj/chaos_shard"
#define NOKICLIFFS_CHAOSBLADE NOKICLIFFS_WEAPONS_DIR + "/chaosblade"
#define NOKICLIFFS_CHAOSDEMON NOKICLIFFS_MONSTERS_DIR + "/chaosdemon"
#define NOKICLIFFS_LAWBRINGER NOKICLIFFS_WEAPONS_DIR + "/lawbringer"
